# fly.toml app configuration file generated for library-project-frontend on 2025-09-18T22:10:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'library-project-frontend'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[env]
  BACKEND_URL = "https://library-project-backend.fly.dev"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
